# Generated by Django 2.2 on 2020-10-24 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proxima_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.CharField(help_text='Phone Format: +254715613745', max_length=13, unique=True),
        ),
    ]
