# Generated by Django 3.1.2 on 2020-10-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('date', models.DateField(auto_now_add=True)),
                ('cover_photo', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(max_length=255)),
            ],
        ),
    ]
