# Generated by Django 3.1.2 on 2020-10-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxima_exped', '0004_auto_20201005_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
