# Generated by Django 3.1.2 on 2020-10-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxima_exped', '0006_auto_20201017_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='person_price',
            field=models.IntegerField(),
        ),
    ]
